# Generated by Django 3.1.7 on 2021-07-07 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WoHeartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('wo_heart_data', models.CharField(blank=True, max_length=100, null=True)),
                ('wo_heart_date', models.DateField(blank=True, null=True)),
                ('wo_heart_day_avg', models.CharField(blank=True, max_length=100, null=True)),
                ('wo_heart_day_max', models.CharField(blank=True, max_length=100, null=True)),
                ('wo_heart_day_min', models.CharField(blank=True, max_length=100, null=True)),
                ('wo_heart_recent', models.CharField(blank=True, max_length=100, null=True)),
                ('wo_heart_sleep_avg', models.CharField(blank=True, max_length=100, null=True)),
                ('wo_heart_sleep_max', models.CharField(blank=True, max_length=100, null=True)),
                ('wo_heart_sleep_min', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gofit_app_woheartinfo_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gofit_app_woheartinfo_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SleepInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('sleep_data', models.CharField(blank=True, max_length=100, null=True)),
                ('sleep_date', models.DateField(blank=True, null=True)),
                ('sleep_deep_time', models.TimeField(blank=True, null=True)),
                ('sleep_light_time', models.TimeField(blank=True, null=True)),
                ('sleep_stayup_time', models.TimeField(blank=True, null=True)),
                ('sleep_total_time', models.TimeField(blank=True, null=True)),
                ('sleep_waking_number', models.IntegerField(blank=True, null=True)),
                ('total_time', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gofit_app_sleepinfo_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gofit_app_sleepinfo_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MotionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('motion_calorie', models.CharField(blank=True, max_length=100, null=True)),
                ('motion_data', models.CharField(blank=True, max_length=100, null=True)),
                ('motion_date', models.DateField(blank=True, null=True)),
                ('motion_distance', models.CharField(blank=True, max_length=100, null=True)),
                ('motion_step', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gofit_app_motioninfo_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gofit_app_motioninfo_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('heart_info_dbp', models.CharField(blank=True, max_length=100, null=True)),
                ('heart_info_hr', models.CharField(blank=True, max_length=100, null=True)),
                ('heart_info_sbp', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gofit_app_heartinfo_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gofit_app_heartinfo_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
