# Generated by Django 3.1.7 on 2021-07-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gofit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motioninfo',
            name='motion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
