# Generated by Django 3.1.7 on 2021-07-22 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gofit_app', '0002_auto_20210715_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartinfo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gofit_app_heartinfo_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='heartinfo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gofit_app_heartinfo_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='motioninfo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gofit_app_motioninfo_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='motioninfo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gofit_app_motioninfo_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sleepinfo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gofit_app_sleepinfo_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sleepinfo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gofit_app_sleepinfo_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='woheartinfo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gofit_app_woheartinfo_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='woheartinfo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gofit_app_woheartinfo_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
