# Generated by Django 3.1.7 on 2021-07-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gofit_app', '0004_auto_20210727_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='woheartinfo',
            name='wo_heart_day_avg',
        ),
        migrations.RemoveField(
            model_name='woheartinfo',
            name='wo_heart_day_max',
        ),
        migrations.RemoveField(
            model_name='woheartinfo',
            name='wo_heart_day_min',
        ),
        migrations.RemoveField(
            model_name='woheartinfo',
            name='wo_heart_recent',
        ),
        migrations.RemoveField(
            model_name='woheartinfo',
            name='wo_heart_sleep_avg',
        ),
        migrations.RemoveField(
            model_name='woheartinfo',
            name='wo_heart_sleep_max',
        ),
        migrations.RemoveField(
            model_name='woheartinfo',
            name='wo_heart_sleep_min',
        ),
        migrations.AlterField(
            model_name='heartinfo',
            name='heart_info_hr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motioninfo',
            name='motion_calorie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motioninfo',
            name='motion_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motioninfo',
            name='motion_step',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepinfo',
            name='total_time',
            field=models.TimeField(blank=True, max_length=100, null=True),
        ),
    ]
