# Generated by Django 3.1.7 on 2021-07-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gofit_app', '0005_auto_20210727_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motioninfo',
            name='motion_calorie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motioninfo',
            name='motion_distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
