# Generated by Django 3.1.7 on 2021-08-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gofit_app', '0006_auto_20210728_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepinfo',
            name='avg_heart_rate',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
