# Generated by Django 3.1.7 on 2021-08-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gofit_app', '0007_sleepinfo_avg_heart_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motioninfo',
            name='motion_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepinfo',
            name='sleep_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='woheartinfo',
            name='wo_heart_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
