# Generated by Django 3.1.13 on 2021-08-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gofit_app', '0008_auto_20210820_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartinfo',
            name='heart_info_dbp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heartinfo',
            name='heart_info_sbp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
