# Generated by Django 3.1.7 on 2021-07-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210621_1202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
