# Generated by Django 3.1.7 on 2021-07-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sleep_goal',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
