# Generated by Django 3.1.7 on 2021-08-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_sleep_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='step_goal',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
