# Generated by Django 3.1.7 on 2021-08-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_step_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='step_goal',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
